name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-nextjs-app .

    - name: Copy build output
      run: |
        docker create --name temp my-nextjs-app
        docker cp temp:/usr/share/nginx/html ./out
        docker rm temp

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./out

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1